### ISSUE TITLE
Update Nette

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#375]
- [x]  pridanie composeru
- [x] tracy/tracy
- [x] nette/utils (v2.5.3): #429 (pt.2) 
- [x] nette/tokenizer (v2.3.0): #448 (pt.7)
- [x] nette/security (v2.4.4): #451 (pt.10)
- [x] nette/safe-stream (v2.3.3): #432 (pt.5) 
- [x] nette/finder (v2.4.2): #450 (pt.9)
- [x] nette/caching (v2.5.8): #453 (pt.12)
- [x] nette/robot-loader (v2.4.4): #453 (pt.12)
- [x] nette/reflection (v2.4.2): #454 (pt.13)
- [x] nette/php-generator (v2.6.4): #455 (pt.14)
- [x] nette/neon (v2.4.3): #449 (pt.8)
- [x] nette/mail (v2.4.6): #434 (pt.6)
- [x] nette/http (v2.4.10): #431 (pt.3)
- [x] nette/component-model (v2.4.0): #430 (pt.4)
- [x] nette/forms (v2.4.9): #516 
- [x] nette/di (v2.4.14): 
- [ ] nette/deprecated (v2.4.2): 
- [x] nette/database (v2.4.8): 
- [x] nette/bootstrap (v2.4.6): 
- [x] nette/application (v2.4.13): 
- [x] latte/latte (v2.4.8): #460 (pt.21)
- [x] nette/nette (v2.4.0):
- [x] nette/tester (v2.0.2): #683

**Comment by cevro** [comment]
- nette/security má problém s cyklickými závislostami
- nette/mail má nepripojné templaty k presenteru
- nette/tokenizer nespolupracuje so starým neonom a lette
